In [48]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

birth = np.loadtxt('births.txt',delimiter=',',dtype=np.int64)

# 1. 남자아이 여자아이 출생 수 평균 정수

year = birth[:,0].mean()
men = birth[:,1].mean()
girl = birth[:,2].mean()

year = int(year)
men = int(men)
girl = int(girl)
print(f'남자아이 출생 평균 : {men}\n여자아이 출생 평균 : {girl}')

print('*'*40)


남자아이 출생 평균 : 1225776
여자아이 출생 평균 : 1245399
****************************************


In [27]:

# 2. 2000년도부터의 데이터를 구하기(2000~2011)

bsize = birth[:,0].size
for i in range(0,bsize):
  if(birth[i][0]>=2000):
    print(birth[i])

print('*'*40)

[   2000 1814601 1962406]
[   2001 1799049 1941251]
[   2002 1795206 1939815]
[   2003 1825359 1973434]
[   2004 1834145 1982794]
[   2005 1845379 1994841]
[   2006 1898463 2052377]
[   2007 1919408 2072139]
[   2008 1887234 2036289]
[   2009 1832925 1979303]
[   2010 1772738 1913851]
[   2011 1753500 1893230]
****************************************


In [34]:
# 남자아이 출생이 가장 많은 년도와 남자아이 출생 수 구하기

'''
# argmax를 사용하여 편하게 찾아낼 수 있음.
# birth[birth[:,1].argmax()]
# y = birth[birth[:,1].argmax()][0]
'''

maxmen = np.max(birth[:,1])
maxyear = birth[birth[:,1]==maxmen][:,0]
print(f'남자아이 출생이 가장 많은 년도 : {maxyear}\n남자 아이 출생 수 : {maxmen}')

print('*'*40)

남자아이 출생이 가장 많은 년도 : [1957]
남자 아이 출생 수 : 2044160
****************************************


In [123]:
# 여자아이 출생이 가장 많은 top5를 구하기 ( 연도, 여자아이 수)

# top5_girls = np.sort(birth[:,2])[-1:-6:-1]
#

maxarr = birth[:,2]
girls = np.sort(maxarr)[::-1]
max5girls = girls[:5]

for i in range(0,max5girls.size):
  max5g=birth[birth[:,2]==max5girls[i],2]
  max5y=birth[birth[:,2]==max5girls[i],0]
  print(f'년도 : {max5y}, 출생 여자아이 수 : {max5g}')

print('*'*40)

년도 : [1957], 출생 여자아이 수 : [2155866]
년도 : [1959], 출생 여자아이 수 : [2133509]
년도 : [1960], 출생 여자아이 수 : [2132717]
년도 : [1961], 출생 여자아이 수 : [2122502]
년도 : [1958], 출생 여자아이 수 : [2120712]
****************************************


In [124]:
# 여자아이 출생률을 구하고, 각 연도별로 여자아이 출생수가 차지하는 비율을 데이터로 구하기(소수점 둘 째 자리까지)
# 여자 출생률 열 추가

birthper = np.array((birth[:,2]/(birth[:,1]+birth[:,2]))).round(2)

'''
# zip 함수를 사용하여 numpy를 사용하지 않고 출력은 가능. (ndarray를 생성하지는 못 함.)
for y,b,g,gr in zip(birth[:,0],birth[:,1],birth[:,2],birthper):
  print(y,b,g,gr,sep=',')
'''

birthper = birthper.reshape(132,1)
newY = np.append(birth,birthper,axis=1)
print(newY)

print('*'*40)

[[   1880.     90993.    110491.         0.55]
 [   1881.     91954.    100745.         0.52]
 [   1882.    107850.    113688.         0.51]
 [   1883.    112321.    104629.         0.48]
 [   1884.    129022.    114445.         0.47]
 [   1885.    133055.    107800.         0.45]
 [   1886.    144535.    110784.         0.43]
 [   1887.    145982.    101414.         0.41]
 [   1888.    178627.    120853.         0.4 ]
 [   1889.    178366.    110584.         0.38]
 [   1890.    190377.    111025.         0.37]
 [   1891.    185482.    101196.         0.35]
 [   1892.    212346.    122037.         0.36]
 [   1893.    212906.    112317.         0.35]
 [   1894.    222922.    115772.         0.34]
 [   1895.    233630.    117398.         0.33]
 [   1896.    237920.    119570.         0.33]
 [   1897.    234202.    112758.         0.32]
 [   1898.    258770.    122693.         0.32]
 [   1899.    233023.    106212.         0.31]
 [   1900.    299828.    150499.         0.33]
 [   1901.   

In [125]:
# 2000년도 이후 데이터에 대해 출생량을 구하고, 남자 아이 수가 180만 이상이면 많음, 아니면 적음 이라는 내용 출력(새 열 생성)

newar = []
y2000 = birth[birth[:,0]>=2000,:]

for i in range(0,y2000[:,0].size):
  if(y2000[i:i+1,1] >= 1800000):
    newar.append('많음')
  else:
    newar.append('적음')

'''

# where 함수를 사용하여 조금 더 편하게 찾아낼 수 있다.
amount = np.where(y2000[:,1]>=1800000,'많음','적음')
print(amount)
'''

arrs = np.array(newar)
arrs = arrs.reshape(12,1)
res = np.append(y2000,arrs,axis=1)
print(res)

print('*'*40)

[['2000' '1814601' '1962406' '많음']
 ['2001' '1799049' '1941251' '적음']
 ['2002' '1795206' '1939815' '적음']
 ['2003' '1825359' '1973434' '많음']
 ['2004' '1834145' '1982794' '많음']
 ['2005' '1845379' '1994841' '많음']
 ['2006' '1898463' '2052377' '많음']
 ['2007' '1919408' '2072139' '많음']
 ['2008' '1887234' '2036289' '많음']
 ['2009' '1832925' '1979303' '많음']
 ['2010' '1772738' '1913851' '적음']
 ['2011' '1753500' '1893230' '적음']]
****************************************


In [ ]:
# 1800,1900,2000 년대의 각 남자아이, 여자아이 출생 수의 평균

y1800s = birth[(birth[:,0]>=1800) & (birth[:,0]<1900)][:,1:]
y1900s = birth[(birth[:,0]>=1900) & (birth[:,0]<2000)][:,1:]
y2000s = birth[(birth[:,0]>=2000)][:,1:]

print(f'1800년대 남자 아이 출생 수 평균 :{y1800s[:,0].mean()}, 여자 아이 출생 수 평균 : {y1800s[:,1].mean()}')
print(f'1900년대 남자 아이 출생 수 평균 :{y1900s[:,0].mean()}, 여자 아이 출생 수 평균 : {y1900s[:,1].mean()}')
print(f'2000년대 남자 아이 출생 수 평균 :{y2000s[:,0].mean():.2f}, 여자 아이 출생 수 평균 : {y2000s[:,1].mean()}')

print('*'*40)

In [ ]:
# 여자아이 출생 수의 25%~ 75% 사이의 값을 구하기 (연도, 여자아이 출생 수)


g_q25 = np.quantile(birth[:,2],0.25)
g_q75 = np.quantile(birth[:,2],0.75)
print(birth[(birth[:,2]>=g_q25) & (birth[:,2]<=g_q75)][:,::2])


print('*'*40)

In [ ]:
# 2000년대에 태어난 남자 아이의 데이터를 bar 차트를 통해 나타내기

import matplotlib.pyplot as plt

y2000boys = birth[birth[:,0]>=2000][:,0:0+2]

plt.bar(y2000boys[:,0],y2000boys[:,1],color='skyblue')
plt.title('2000s boys birth')
plt.xlabel('year')
plt.ylabel('birth')
plt.show()